name: frontend
description: "GrowIse - Child Growth Tracking App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # HTTP calls to backend
  http: ^1.2.0
  # Charts
  fl_chart: ^0.68.0
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true