name: growise
description: "Growise - Child Growth & Health App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management + navigation + DI
  get: ^4.6.6

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # HTTP
  dio: ^5.7.0
  http: ^1.2.2

  # URL + video
  url_launcher: ^6.3.1
  video_player: ^2.9.2

  # Charts
  fl_chart: ^0.69.0

  # Connectivity
  connectivity_plus: ^6.1.0

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
