// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBknQsfcIlYHkfJ4fBAyj_8cburr2O7M2M',
    appId: '1:649386560812:web:13cfb37825235ff3d5f089',
    messagingSenderId: '649386560812',
    projectId: 'growise-73261',
    authDomain: 'growise-73261.firebaseapp.com',
    storageBucket: 'growise-73261.firebasestorage.app',
    measurementId: 'G-37EX0E83P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSfjIU-xsXGZudmhgLmLgaDhq0SEJuIw',
    appId: '1:649386560812:android:d709b3a1b282d547d5f089',
    messagingSenderId: '649386560812',
    projectId: 'growise-73261',
    storageBucket: 'growise-73261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xfGS8zwklXI5HiuXqlaFcJ2SerPqSFw',
    appId: '1:649386560812:ios:344ff2dde5e4660dd5f089',
    messagingSenderId: '649386560812',
    projectId: 'growise-73261',
    storageBucket: 'growise-73261.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xfGS8zwklXI5HiuXqlaFcJ2SerPqSFw',
    appId: '1:649386560812:ios:344ff2dde5e4660dd5f089',
    messagingSenderId: '649386560812',
    projectId: 'growise-73261',
    storageBucket: 'growise-73261.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBknQsfcIlYHkfJ4fBAyj_8cburr2O7M2M',
    appId: '1:649386560812:web:13cfb37825235ff3d5f089',
    messagingSenderId: '649386560812',
    projectId: 'growise-73261',
    authDomain: 'growise-73261.firebaseapp.com',
    storageBucket: 'growise-73261.firebasestorage.app',
    measurementId: 'G-37EX0E83P9',
  );

}